spring.application.name=cinebook

SPRING_DATASOURCE_URL=jdbc:postgresql://ep-small-tree-aj13dkxd.c-3.us-east-2.aws.neon.tech/neondb?sslmode=require
SPRING_DATASOURCE_USERNAME=neondb_owner
SPRING_DATASOURCE_PASSWORD=yourpass

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.format_sql = true
jwt.secret=${JWT_SECRET}